version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: linkritback-db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: linkritback_local
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: